# Generated by Django 3.2.3 on 2021-06-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_per_day', models.FloatField(max_length=500)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesapi.usersprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie', models.FloatField()),
                ('meals', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('calorie_per_day', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caloriesapi.usersprofile')),
            ],
        ),
    ]
