# Generated by Django 3.2.3 on 2021-06-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caloriesapi', '0002_calorie_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calorie',
            old_name='text',
            new_name='calorie_note',
        ),
    ]
