# Generated by Django 3.2.3 on 2021-06-10 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caloriesapi', '0003_rename_text_calorie_calorie_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='usersetting',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
